glucosetracker/core/urls.py
from django.conf.urls import patterns, url

from .views import HelpPageView


urlpatterns = patterns('',
    url(
        regex=r'^help/',
        view=HelpPageView.as_view(),
        name='help',
    ),
)

glucosetracker/glucoses/urls.py
from django.conf.urls import patterns, url

from .views import (
    import_data,
    filter_view,
    quick_add,
    stats_json,
    chart_data_json,
    GlucoseChartsView,
    GlucoseCreateView,
    GlucoseUpdateView,
    GlucoseDeleteView,
    GlucoseEmailReportView,
    GlucoseListJson,
)


urlpatterns = patterns('',
    url(
        regex=r'^import/',
        view=import_data,
        name='glucose_import',
    ),
    url(
        regex=r'^filter/',
        view=filter_view,
        name='glucose_filter',
    ),
    url(
        regex=r'^quick_add/',
        view=quick_add,
        name='glucose_quick_add',
    ),
    url(
        regex=r'^add/',
        view=GlucoseCreateView.as_view(),
        name='glucose_create',
    ),
    url(
        regex=r'^list_json/$',
        view=GlucoseListJson.as_view(),
        name='glucose_list_json',
    ),
    url(
        regex=r'^chart_data_json/$',
        view=chart_data_json,
        name='chart_data_json',
    ),
    url(
        regex=r'^stats_json/$',
        view=stats_json,
        name='stats_json',
    ),
    url(
        regex=r'^charts/$',
        view=GlucoseChartsView.as_view(),
        name='glucose_charts',
    ),
    url(
        regex=r'^email_report/',
        view=GlucoseEmailReportView.as_view(),
        name='glucose_email_report',
    ),
    url(
        regex=r'^(?P<pk>\d+)/edit/',
        view=GlucoseUpdateView.as_view(),
        name='glucose_update',
    ),
    url(
        regex=r'^(?P<pk>\d+)/delete/',
        view=GlucoseDeleteView.as_view(),
        name='glucose_delete',
    ),
)

glucosetracker/glucoses/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User

from taggit.managers import TaggableManager

from core.models import TimeStampedModel


class GlucoseManager(models.Manager):

    def by_user(self, user, **kwargs):
        """
        Filter objects by the 'user' field.
        """
        return self.select_related().filter(user=user)

    def by_date(self, start_date, end_date, user, **kwargs):
        """
        Filter objects by date range.
        """
        resultset = self.by_user(user).filter(
            record_date__gte=start_date,
            record_date__lte=end_date,
        )

        return resultset.order_by('-record_date', '-record_time')

    def level_breakdown(self, start_date, end_date, user, **kwargs):
        """
        Filter objects by glucose level and count the records for each level.

        The range for the different levels are specified in the user's
        settings.
        """
        user_settings = user.settings
        low = user_settings.glucose_low
        high = user_settings.glucose_high
        target_min = user_settings.glucose_target_min
        target_max = user_settings.glucose_target_max

        data = self.by_date(start_date, end_date, user)
        all_count = data.count()
        low_count = data.filter(value__lte=low).count()
        high_count = data.filter(value__gte=high).count()
        target_count = data.filter(
            value__gte=target_min, value__lte=target_max).count()

        result = {
            'Low': low_count,
            'High': high_count,
            'Within Target': target_count,
            'Other': all_count - (low_count + high_count + target_count)
        }

        return result

    def by_category(self, start_date, end_date, user, **kwargs):
        """
        Group objects by category and take the count.
        """
        data = self.by_date(start_date, end_date, user)

        return data.values('category__name')\
            .annotate(count=models.Count('value'))\
            .order_by('category')

    def avg_by_category(self, start_date, end_date, user):
        """
        Group objects by category and take the average of the values.
        """
        data = self.by_date(start_date, end_date, user)

        return data.values('category__name')\
            .annotate(avg_value= models.Avg('value'))\
            .order_by('category')

    def avg_by_day(self, start_date, end_date, user):
        """
        Group objects by record date and take the average of the values.
        """
        data = self.by_date(start_date, end_date, user)

        return data.values('record_date')\
            .annotate(avg_value= models.Avg('value'))\
            .order_by('record_date')


class Glucose(TimeStampedModel):
    objects = GlucoseManager()

    user = models.ForeignKey(User)
    value = models.PositiveIntegerField(validators=[MaxValueValidator(54054),
                                                    MinValueValidator(0)])
    category = models.ForeignKey('Category')
    record_date = models.DateField('Date')
    record_time = models.TimeField('Time')
    notes = models.TextField('Notes', null=False, blank=True, default='')
    tags = TaggableManager(blank=True, help_text=None)

    def __unicode__(self):
        return str(self.value)

    class Meta:
        ordering = ['-record_date', '-record_time']


class Category(models.Model):
    name = models.CharField(unique=True, max_length=255)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ['id']


class Unit(models.Model):
    name = models.CharField(unique=True, max_length=6)

    def __unicode__(self):
        return self.name

glucosetracker/glucoses/forms.py
import itertools
from datetime import date, timedelta

from django import forms
from django.core.urlresolvers import reverse

from crispy_forms.helper import FormHelper, Layout
from crispy_forms.layout import Button, Submit, MultiField, Div, HTML, \
    Field, Fieldset, Reset
from crispy_forms.bootstrap import FormActions

from .models import Glucose, Category
from .fields import RestrictedFileField


DATE_FORMAT = '%m/%d/%Y'
TIME_FORMAT = '%I:%M %p'


class GlucoseFilterForm(forms.Form):
    quick_date_select = forms.ChoiceField(
        label='Quick Date Select',
        choices=(
            (7, 'Last 7 Days'),
            (30, 'Last 30 Days'),
            (60, 'Last 60 Days'),
            (90, 'Last 90 Days'),
        ),
        required=False,
    )
    start_date = forms.DateField(
        label='Date Range', required=False, input_formats=[DATE_FORMAT])
    end_date = forms.DateField(
        label='', required=False, input_formats=[DATE_FORMAT])

    start_value = forms.IntegerField(
        label='Value Range', required=False, min_value=0)
    end_value = forms.IntegerField(label='', required=False, min_value=0)

    category = forms.ModelChoiceField(
        queryset=Category.objects.all(), required=False)

    notes = forms.CharField(label='Notes Contains', required=False,
                            widget=forms.Textarea(attrs={'rows': 2}))

    def __init__(self, user, *args, **kwargs):
        super(GlucoseFilterForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_id = 'filter_form'
        self.helper.form_method = 'post'
        self.helper.form_action = '.'

        self.fields['tags'] = forms.ChoiceField(
            choices=self.get_tags(Glucose.objects.filter(user=user).exclude(
                tags__name__isnull=True)),
            required=False)

        self. helper.layout = Layout(
            'quick_date_select',
            Field('start_date', placeholder='From (mm/dd/yyyy)'),
            Field('end_date', placeholder='To (mm/dd/yyyy)'),
            'category',
            Field('start_value', placeholder='From', step='any'),
            Field('end_value', placeholder='To', step='any'),
            'notes',
            Field('tags'),
            FormActions(
                Submit('submit', 'Filter'),
                Reset('reset', 'Reset'),
            ),
        )

    def get_tags(self, queryset):
        """
        Iterate through the queryset and get the unique tag names.
        """
        tag_list = list(itertools.chain.from_iterable(
            [i.tags.names() for i in queryset]))

        empty_label = [('', '---------')]
        # The tag_list here is converted to a set to create a unique
        # collection.
        choices = empty_label + [
            (tag, tag) for tag in sorted(list(set(tag_list)))]

        return choices


class GlucoseQuickAddForm(forms.ModelForm):
    """
    A simple form for adding glucose values. Date and time are automatically
    set to the user's current local date and time using Javascript (see
    dashboard.html template).
    """
    def __init__(self, *args, **kwargs):
        super(GlucoseQuickAddForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_id = 'quick_add_form'
        self.helper.form_method = 'post'
        self.helper.form_class = 'form-inline'
        self.helper.form_show_labels = False

        # Remove the blank option from the select widget.
        self.fields['category'].empty_label = None

        self.helper.layout = Layout(
            HTML('''
            <div id="div_id_value" class="form-group"> <div class="controls">
            <input autofocus="True" class="numberinput form-control"
            id="id_value" name="value"
            placeholder="Value ({{ user.settings.glucose_unit.name }})"
            required="True" type="number" step="any" min="0"/></div></div>
            '''),
            Field('category'),
            Field('record_date', type='hidden'),
            Field('record_time', type='hidden'),
            Submit('submit', 'Quick Add'),
        )

    class Meta:
        model = Glucose
        exclude = ('user', 'notes')


class GlucoseEmailReportForm(forms.Form):
    report_format = forms.ChoiceField(
        label='Format',
        choices=(
            ('csv', 'CSV'),
            ('pdf', 'PDF'),
        )
    )
    start_date = forms.DateField(label='From')
    end_date = forms.DateField(label='To')
    subject = forms.CharField(required=False)
    recipient = forms.EmailField(label='Send To')
    message = forms.CharField(widget=forms.Textarea(attrs={'cols':50}),
                              required=False)

    def __init__(self, *args, **kwargs):
        super(GlucoseEmailReportForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-sm-3 col-md-3'
        self.helper.field_class = 'col-sm-9 col-md-9'

        self. helper.layout = Layout(
            MultiField(
                None,
                Div(
                    HTML('''
                    {% if messages %}
                    {% for message in messages %}
                    <p {% if message.tags %}
                    class="alert alert-{{ message.tags }}"
                    {% endif %}>{{ message }}</p>{% endfor %}{% endif %}
                    '''),
                    Div(
                        'report_format',
                        Field('start_date', required=True),
                        Field('end_date', required=True),
                        css_class='well col-sm-4 col-md-4',
                    ),
                    Div('subject',
                        Field('recipient', placeholder='Email address',
                              required=True, autofocus=True),
                        'message',
                        FormActions(
                            Submit('submit', 'Send'),
                            css_class='pull-right'
                        ),
                        css_class='col-sm-8 col-md-8',
                    ),
                    css_class='row'
                ),
            ),
        )

        # Initial values.
        now = date.today()
        last_90_days = now - timedelta(days=90)
        self.fields['start_date'].initial = last_90_days.strftime(DATE_FORMAT)
        self.fields['end_date'].initial = now.strftime(DATE_FORMAT)

        self.fields['report_format'].initial = 'pdf'
        self.fields['subject'].initial = '[GlucoseTracker] Glucose Data Report'


class GlucoseInputForm(forms.ModelForm):
    # This is a hidden field that holds the submit type value. Used to
    # determine whether the user clicked 'Save' or 'Save & Add Another' in
    # the Glucose Create Form.
    submit_button_type = forms.CharField(required=False)

    def __init__(self, *args, **kwargs):
        super(GlucoseInputForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_class = 'form-horizontal col-xs-12 col-md-6 col-lg-5'
        self.helper.label_class = 'col-xs-3 col-md-2 col-lg-2'
        self.helper.field_class = 'col-xs-9 col-md-10 col-lg-10'
        self.helper.add_input(Submit('submit', 'Save'))
        self.helper.add_input(Button(
            'cancel', 'Cancel', onclick='location.href="%s";' % \
                                        reverse('dashboard')))

        # Remove the blank option from the select widget.
        self.fields['category'].empty_label = None
        self.fields['category'].required = False

        # Specify which time formats are valid for this field. This setting is
        # necessary when using the bootstrap-datetimepicker widget as it
        # doesn't allow inputting of seconds.
        valid_time_formats = ['%H:%M', '%I:%M%p', '%I:%M %p']
        self.fields['record_time'].input_formats = valid_time_formats

        self. helper.layout = Layout(
            HTML(
                '''
                {% if messages %}
                {% for message in messages %}
                <p {% if message.tags %}
                class="alert alert-{{ message.tags }}"
                {% endif %}>{{ message }}</p>{% endfor %}{% endif %}
                '''
            ),
            Field('value', placeholder='Value', required=True, autofocus=True,
                  min=0, step='any'),
            'category',
            'record_date',
            'record_time',
            'notes',
            Field('tags', placeholder='e.g. fasting, sick, "after meal"'),
            Field('submit_button_type', type='hidden')
        )


    class Meta:
        model = Glucose
        exclude = ('user',)
        widgets = {
            'notes': forms.Textarea(attrs={'rows': 4}),
        }


class GlucoseCreateForm(GlucoseInputForm):

    def __init__(self, *args, **kwargs):
        super(GlucoseCreateForm, self).__init__(*args, **kwargs)

        # Make record date and time not required. If these fields are empty
        # the current date and time will be used.
        self.fields['record_date'].required = False
        self.fields['record_time'].required = False

        self.helper.add_input(Submit('submit_and_add', 'Save & Add Another',
                                     css_class='pull-right'))


class GlucoseUpdateForm(GlucoseInputForm):

    def __init__(self, *args, **kwargs):
        super(GlucoseUpdateForm, self).__init__(*args, **kwargs)

        # Set date and time formats to those supported by the
        # bootstrap-datetimepicker widget.
        self.fields['record_date'].widget.format = DATE_FORMAT
        self.fields['record_time'].widget.format = TIME_FORMAT

        delete_url = reverse('glucose_delete', args=(self.instance.id,))
        self.helper.add_input(Button('delete', 'Delete',

glucosetracker/templates/glucoses/glucose_confirm_delete.html
{% extends 'base.html' %}

{% block heading %}<h3>
    <span class="glyphicon glyphicon-remove"></span> Delete Glucose</h3>{% endblock %}

{% block content %}
<div class="form-group">
    <form action="{% url 'glucose_delete' glucose.id %}" method="post">
        {% csrf_token %}
        <p>Deleting glucose <b>{{ glucose.value }} ({{ glucose.category }})</b>. Are you sure?</p>
        <br>
        <button type="submit" class="btn btn-primary" action="submit">Yes, I'm sure</button>
        <button type="button" class="btn" onclick="location.href=&quot;{% url 'dashboard' %}&quot;;">Cancel</button>
    </form>
</div>
{% endblock %}

glucosetracker/templates/glucoses/glucose_create.html
{% extends 'base.html' %}

{% block heading %}
    <h3><span class="glyphicon glyphicon-plus"></span> Add Glucose</h3>
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
   {% crispy form %}
{% endblock %}

{% block extrajs %}
<script type="text/javascript">
$(function () {
    $('#id_record_date').datetimepicker({
        pickTime: false
    });

    // Sets the value of the submit_button_type field if the 'Submit & Add
    // Another button is clicked.
    $('#submit-id-submit_and_add').click(function() {
        $('#id_submit_button_type').val('submit_and_add');
    });
});

</script>
{% endblock %}

glucosetracker/templates/glucoses/glucose_email_report.html
{% extends 'base.html' %}

{% block extracss %}
<link href="{{ STATIC_URL }}datetimepicker/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
{% endblock %}

{% block heading %}
<h3>
    <span class="glyphicon glyphicon-envelope"></span> Email Report
    <small>
        <a href="{% url 'glucose_filter' %}">Filter Data</a>
        | <a href="{% url 'glucose_charts' %}">Charts & Graphs</a>
    </small>
</h3>
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
   {% crispy form %}
</div>
{% endblock %}

{% block extrajs %}
<script type="text/javascript">
$(function () {
    $('#id_start_date').datetimepicker({
        pickTime: false
    });

    $('#id_end_date').datetimepicker({
        pickTime: false
    });
});
</script>
{% endblock %}

glucosetracker/templates/glucoses/glucose_filter.html
{% extends 'base.html' %}

{% block heading %}
<h3>
    <span class="glyphicon glyphicon-filter"></span> Filter Data
    <small>
        <a href="{% url 'glucose_charts' %}">Charts & Graphs</a>
        | <a href="{% url 'glucose_email_report' %}">Email Report</a>
    </small>
</h3>
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="row">

        <div class="col-sm-4 col-md-4">
            <div id="accordion" class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a class="accordion-toggle" data-toggle="collapse" data-target="#collapseBody">
                        Options<span class="glyphicon glyphicon-chevron-up pull-right"></span>
                    </a>
                </h4>
            </div>
            <div id="collapseBody" class="panel-collapse collapse in">
                <div class="panel-body">
                    {% crispy form %}
                </div>
            </div>
            </div>
        </div>

        <div class="col-sm-8 col-md-8">
            <div class="well">
                <table id="glucose_table">
                    <thead>
                        <tr>
                            <th width="10%"><center>Value</center></th>
                            <th width="15%">Category</th>
                            <th width="15%">Date</th>
                            <th width="15%">Time</th>
                            <th width="35%">Notes</th>
                            <th width="10%"></th>
                        </tr>
                    </thead>
                </table>
                <br>
            </div>
        </div>

    </div>
</div>
{% endblock %}

{% block extracss %}
<link href="{{ STATIC_URL }}datatables/media/css/jquery.dataTables.css" rel="stylesheet">
<link href="{{ STATIC_URL }}datatables/extras/TableTools/media/css/TableTools.css" rel="stylesheet">
{% endblock %}

{% block extrajs %}
<script src="{{ STATIC_URL }}datatables/media/js/jquery.dataTables.min.js"></script>
<script src="{{ STATIC_URL }}datatables/extras/TableTools/media/js/TableTools.min.js"></script>
<script src="{{ STATIC_URL }}scripts/scripts.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    var oTable = $('#glucose_table').dataTable( {
        "sDom": 'T<"clear">lrtip',
        "oTableTools": {
            "sSwfPath": "{{ STATIC_URL }}datatables/extras/TableTools/media/swf/copy_csv_xls_pdf.swf",
            "aButtons": [ "csv", "pdf", "print" ]
        },
        "aLengthMenu": [
            [10, 25, 50, 100, 200, 300],
            [10, 25, 50, 100, 200, 300],
        ],
        "iDisplayLength": 25,
        "bProcessing": true,
        "bServerSide": true,
        "sAjaxSource": "{{ data }}",
        "aaSorting": [ [2,'desc'], [3,'desc']],
        // Disable sorting for the Actions column.
        "aoColumnDefs": [ { "bSortable": false, "aTargets": [ 5 ] } ]
    });

    // Submit the filter form and refresh the table data
    var frm = $('#filter_form');
    frm.submit(function () {
        $.ajax({
            type: frm.attr('method'),
            url: frm.attr('action'),
            data: frm.serialize(),
            success: function (data) {
                // Reload the table data. This function is located in
                // scripts/scripts.js.
                oTable.fnReloadAjax(data);

                // Re-enable the submit button.
                $('#submit-id-submit').prop('disabled', false);
            },
            error: function(data) {
                alert('Sorry, something went wrong. Please try again.');
            }
        });
        return false;
    });


    // For changing the icon in the Options panel
    $('.collapse').on('shown.bs.collapse', function(){
        $(this).parent().find(".glyphicon-chevron-down")
            .removeClass("glyphicon-chevron-down")
            .addClass("glyphicon-chevron-up");
    }).on('hidden.bs.collapse', function(){
        $(this).parent().find(".glyphicon-chevron-up")
            .removeClass("glyphicon-chevron-up")
            .addClass("glyphicon-chevron-down");
    });

    $('#id_start_date').datetimepicker({
        pickTime: false
    });

    $('#id_end_date').datetimepicker({
        pickTime: false
    });

    // Change start_date value when select field value changes.
    $('#id_quick_date_select').change(function(){
        var currentDate = new Date();
        currentDate.setDate(currentDate.getDate() -
            $('#id_quick_date_select').val());
        var dateString = (currentDate.getMonth()+1) + "/"
            + currentDate.getDate() + "/"
            + currentDate.getFullYear();

        $('#id_start_date').val(dateString);
    });
});
</script>
{% endblock %}

glucosetracker/templates/glucoses/glucose_import.html
{% extends 'base.html' %}

{% block heading %}
<h3>
    <span class="glyphicon glyphicon-import"></span> Import Data from CSV
    <small>
        <a href="{% url 'help' %}">Help</a>
    </small>
</h3>
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
   {% crispy form %}
</div>
{% endblock %}

glucosetracker/templates/glucoses/glucose_update.html
{% extends 'base.html' %}

{% block heading %}
    <h3><span class="glyphicon glyphicon-pencil"></span> Edit Glucose</h3>
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
   {% crispy form %}
{% endblock %}

{% block extrajs %}
<script type="text/javascript">
$(function () {
    $('#id_record_date').datetimepicker({
        pickTime: false
    });
});
</script>
{% endblock %}