glucosetracker/core/urls.py
from django.conf.urls import patterns, url

from .views import HelpPageView


urlpatterns = patterns('',
    url(
        regex=r'^help/',
        view=HelpPageView.as_view(),
        name='help',
    ),
)

glucosetracker/core/models.py
from django.db import models


class TimeStampedModel(models.Model):
    """
    Abstract base class that provides self-updating 'created' and 'modified'
    fields.
    """
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

glucosetracker/glucoses/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User

from taggit.managers import TaggableManager

from core.models import TimeStampedModel


class GlucoseManager(models.Manager):

    def by_user(self, user, **kwargs):
        """
        Filter objects by the 'user' field.
        """
        return self.select_related().filter(user=user)

    def by_date(self, start_date, end_date, user, **kwargs):
        """
        Filter objects by date range.
        """
        resultset = self.by_user(user).filter(
            record_date__gte=start_date,
            record_date__lte=end_date,
        )

        return resultset.order_by('-record_date', '-record_time')

    def level_breakdown(self, start_date, end_date, user, **kwargs):
        """
        Filter objects by glucose level and count the records for each level.

        The range for the different levels are specified in the user's
        settings.
        """
        user_settings = user.settings
        low = user_settings.glucose_low
        high = user_settings.glucose_high
        target_min = user_settings.glucose_target_min
        target_max = user_settings.glucose_target_max

        data = self.by_date(start_date, end_date, user)
        all_count = data.count()
        low_count = data.filter(value__lte=low).count()
        high_count = data.filter(value__gte=high).count()
        target_count = data.filter(
            value__gte=target_min, value__lte=target_max).count()

        result = {
            'Low': low_count,
            'High': high_count,
            'Within Target': target_count,
            'Other': all_count - (low_count + high_count + target_count)
        }

        return result

    def by_category(self, start_date, end_date, user, **kwargs):
        """
        Group objects by category and take the count.
        """
        data = self.by_date(start_date, end_date, user)

        return data.values('category__name')\
            .annotate(count=models.Count('value'))\
            .order_by('category')

    def avg_by_category(self, start_date, end_date, user):
        """
        Group objects by category and take the average of the values.
        """
        data = self.by_date(start_date, end_date, user)

        return data.values('category__name')\
            .annotate(avg_value= models.Avg('value'))\
            .order_by('category')

    def avg_by_day(self, start_date, end_date, user):
        """
        Group objects by record date and take the average of the values.
        """
        data = self.by_date(start_date, end_date, user)

        return data.values('record_date')\
            .annotate(avg_value= models.Avg('value'))\
            .order_by('record_date')


class Glucose(TimeStampedModel):
    objects = GlucoseManager()

    user = models.ForeignKey(User)
    value = models.PositiveIntegerField(validators=[MaxValueValidator(54054),
                                                    MinValueValidator(0)])
    category = models.ForeignKey('Category')
    record_date = models.DateField('Date')
    record_time = models.TimeField('Time')
    notes = models.TextField('Notes', null=False, blank=True, default='')
    tags = TaggableManager(blank=True, help_text=None)

    def __unicode__(self):
        return str(self.value)

    class Meta:
        ordering = ['-record_date', '-record_time']


class Category(models.Model):
    name = models.CharField(unique=True, max_length=255)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ['id']


class Unit(models.Model):
    name = models.CharField(unique=True, max_length=6)

    def __unicode__(self):
        return self.name

glucosetracker/core/forms.py
from django import forms

from crispy_forms.helper import FormHelper, Layout
from crispy_forms.layout import Submit, Fieldset, HTML, Field
from crispy_forms.bootstrap import FormActions


class ContactForm(forms.Form):
    email = forms.EmailField(label='Your Email Address')
    subject = forms.CharField(required=False)
    message = forms.CharField(widget=forms.Textarea(
        attrs={'cols': 50, 'rows': 6}))

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_class = 'col-xs-12 col-md-6'

        self. helper.layout = Layout(
            HTML('''
            {% if messages %}
            {% for message in messages %}
            <p {% if message.tags %} class="alert alert-{{ message.tags }}"\
            {% endif %}>{{ message }}</p>{% endfor %}{% endif %}
            </p>
            '''),
            Fieldset(
                'Contact Us',
                Field('email'),
                Field('subject'),
                Field('message'),
            ),
            FormActions(Submit('submit', 'Send', css_class='pull-right'))
        )

glucosetracker/core/views.py
from django.views.generic import TemplateView, FormView
from django.contrib import messages
from django.core.mail import EmailMessage
from django.conf import settings

from braces.views import LoginRequiredMixin

from glucoses.models import Glucose

from .forms import ContactForm


class HomePageView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        context['glucose_count'] = Glucose.objects.count()

        return context


class HelpPageView(LoginRequiredMixin, FormView):
    success_url = '.'
    form_class = ContactForm
    template_name = 'core/help.html'

    def get_initial(self):
        return {
            'email': self.request.user.email
        }

    def form_valid(self, form):
        success_message = '''Email sent! We'll try to get back to you as
            soon as possible.'''
        messages.add_message(self.request, messages.SUCCESS, success_message)

        return super(HelpPageView, self).form_valid(form)

    def form_invalid(self, form):
        failure_message = 'Email not sent. Please try again.'
        messages.add_message(self.request, messages.WARNING, failure_message)

        return super(HelpPageView, self).form_invalid(form)

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        if form.is_valid():
            support_email = settings.CONTACTS['support_email']

            message = 'Sent By: %s (%s)\n\n%s' % (
                form.cleaned_data['email'],
                self.request.user.username,
                form.cleaned_data['message'])

            email = EmailMessage(
                from_email=support_email,
                subject='[Help] %s ' % form.cleaned_data['subject'],
                body=message,
                to=[support_email])

            email.send()

            return self.form_valid(form)
        else:
            return self.form_invalid(form)

glucosetracker/templates/core/dashboard.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block heading %}
    <h3><span class="glyphicon glyphicon-th"></span> Dashboard</h3>
{% endblock %}

{% block content %}
<div class="container">
{% if sticky_message %}
    <div class="alert alert-info alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        {{ sticky_message.message|safe }}
    </div>
{% endif %}
    
    <div class="row">
        <div class="col-sm-12 col-md-12">
            <div class="btn-toolbar well" role="toolbar">
                <div class="btn-group">
                    <a href="{% url 'glucose_create'%}">
                    <button type="button" class="btn btn-primary">
                        <span class="glyphicon glyphicon-plus"></span> New Glucose</button>
                    </a>
                </div>
                <div class="btn-group">
                    <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
                    <span class="glyphicon glyphicon-stats"></span> Reports
                    <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'glucose_filter' %}">Filter Data</a></li>
                    <li><a href="{% url 'glucose_charts' %}">Charts & Graphs</a></li>
                    <li class="divider"></li>
                    <li><a href="{% url 'glucose_email_report' %}">E-mail Report</a></li>
                    </ul>
                </div>
                <div class="pull-right">{% crispy form %}</div>
            </div>
        </div>
    </div> <!-- end row -->

    <div class="row">
        <div class="col-sm-6 col-md-6">
            <div class="row">
                <div class="col-sm-6 col-md-6">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h5 class="panel-title text-center">
                                <b>Latest Reading</b>
                            </h5>
                        </div>
                        <div class="panel-body">
                            <h3 id="id_latest_entry"></h3>
                            <p id="id_twitter_button" class="text-center"></p>
                        </div>
                    </div>
                </div>

                <div class="col-sm-6 col-md-6">
                    <div class="panel panel-default">
                        <div id="id_hba1c_panel" class="panel-heading" data-toggle="tooltip"
                             title="Based on the average blood glucose from the last 90 days.">
                            <h3 class="panel-title text-center">
                                <b>HbA1c Estimate*</b>
                            </h3>
                        </div>
                        <div class="panel-body" style="padding-bottom:24px">
                            <h3 id="id_hba1c"></h3>
                        </div>
                    </div>
                </div>
            </div> <!-- end row -->

            <div class="row">
                <div class="col-sm-12 col-md-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title text-center">
                                <b>14-Day Breakdown</b>
                            </h3>
                        </div>
                        <table class="table table-condensed">
                            <tr>
                                <td><b>Lows</b></td>
                                <td id="id_lows"></td>
                                <td><b>Lowest</b></td>
                                <td id="id_lowest" align="right"></td>
                            </tr>
                            <tr>
                                <td><b>Highs</b></td>
                                <td id="id_highs"></td>
                                <td><b>Highest</b></td>
                                <td id="id_highest" align="right"></td>
                            </tr>
                            <tr>
                                <td><b>Within Target</b></td>
                                <td id="id_within_target"></td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td><b>Other</b></td>
                                <td id="id_other"></td>
                                <td><b>Average</b></td>
                                <td id="id_average" align="right"></td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div> <!-- end row -->
        </div> <!-- end col -->

        <div class="col-sm-6 col-md-6">
            <div class="panel panel-default">
                <div id="chart_panel" class="panel-body" style="width:100%;height:343px"></div>
            </div>
        </div> <!--end col -->

    </div> <!-- end row -->
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-12">
            <div class="well">
                <table id="glucose_table">
                    <thead>
                        <tr>
                            <th width="10%"><center>Value</center></th>
                            <th width="15%">Category</th>
                            <th width="15%">Date</th>
                            <th width="15%">Time</th>
                            <th width="35%">Notes</th>
                            <th width="10%"></th>
                        </tr>
                    </thead>
                </table><br>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extracss %}
<link href="{{ STATIC_URL }}datatables/media/css/jquery.dataTables.css" rel="stylesheet">
<link href="{{ STATIC_URL }}datatables/extras/TableTools/media/css/TableTools.css" rel="stylesheet">
{% endblock %}

{% block extrajs %}
<script src="{{ STATIC_URL }}datatables/media/js/jquery.dataTables.min.js"></script>
<script src="{{ STATIC_URL }}datatables/extras/TableTools/media/js/TableTools.min.js"></script>
<script src="{{ STATIC_URL }}highcharts/js/highcharts.js"></script>
<script src="{{ STATIC_URL }}highcharts/js/modules/exporting.js"></script>
<script src="{{ STATIC_URL }}scripts/scripts.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    $('#id_hba1c_panel').tooltip();

    // Update stats in panels
    var statsUrl = "{% url 'stats_json' %}";
    function loadStats() {
        $.getJSON(statsUrl,
            function(data) {
                document.getElementById('id_latest_entry').innerHTML =
                    data['stats']['latest_entry']['value'];
                document.getElementById('id_latest_entry').className =
                    "text-center " + data['stats']['latest_entry']['css_class'];

                document.getElementById('id_hba1c').innerHTML =
                    data['stats']['hba1c']['value'];
                document.getElementById('id_hba1c').className =
                    "text-center " + data['stats']['hba1c']['css_class'];
                    
                /*document.getElementById('id_num_records').innerHTML =
                    data['stats']['num_records'];*/

                document.getElementById('id_lowest').innerHTML =
                    data['stats']['breakdown']['lowest']['value'];
                document.getElementById('id_lowest').className =
                    data['stats']['breakdown']['lowest']['css_class'];
                    
                document.getElementById('id_highest').innerHTML =
                    data['stats']['breakdown']['highest']['value'];
                document.getElementById('id_highest').className =
                    data['stats']['breakdown']['highest']['css_class'];
                    
                document.getElementById('id_average').innerHTML =
                    data['stats']['breakdown']['average']['value'];
                document.getElementById('id_average').className =
                    data['stats']['breakdown']['average']['css_class'];

                document.getElementById('id_highs').innerHTML =
                    data['stats']['breakdown']['highs'];
                document.getElementById('id_lows').innerHTML =
                    data['stats']['breakdown']['lows'];
                document.getElementById('id_within_target').innerHTML =
                    data['stats']['breakdown']['within_target'];
                document.getElementById('id_other').innerHTML =
                    data['stats']['breakdown']['other'];

                var twitter_text = "#bgnow "
                    + data['stats']['latest_entry']['value']
                    + " (" + data['stats']['latest_entry']['record_time']
                    + ") " + data['stats']['latest_entry']['notes'];
                // Remove leading and trailing spaces
                twitter_text = twitter_text.trim();
                updateTwitterValues(twitter_text, 'glucosetracker');
            }
        )};

    loadStats();


    // Glucose Average by Day chart
     var avgByDayOptions = {
        chart: {
            renderTo: 'chart_panel',
            type: 'line',
        },
        legend: {enabled: false},
        title: {text: 'Average Glucose by Day'},
        subtitle: {text: 'Last 14 Days'},
        xAxis: {title: {text: null}, labels: {rotation: -45}},
        yAxis: {title: {text: null}},
        series: [{}],
    };

    var chartDataUrl = "{% url 'chart_data_json' %}?name=avg_by_day&days=14";
    function loadChart() {
        $.getJSON(chartDataUrl,
            function(data) {
                avgByDayOptions.xAxis.categories = data['chart_data']['dates'];
                avgByDayOptions.series[0].name = 'Avg Glucose ({{ user.settings.glucose_unit }})';
                avgByDayOptions.series[0].data = data['chart_data']['values'];
                var chart = new Highcharts.Chart(avgByDayOptions);
         });
     }

    loadChart();


    var oTable = $('#glucose_table').dataTable( {
        "sDom": 'T<"clear">lrtip',
        "oTableTools": {
            "sSwfPath": "{{ STATIC_URL }}datatables/extras/TableTools/media/swf/copy_csv_xls_pdf.swf",
		    "aButtons": [ "csv", "pdf", "print" ]
        },
        "bProcessing": true,
        "bServerSide": true,
        "sAjaxSource": "{% url 'glucose_list_json' %}",
        "aaSorting": [ [2,'desc'], [3,'desc'] ],
        // Disable sorting for the Actions column.
        "aoColumnDefs": [ { "bSortable": false, "aTargets": [ 5 ] } ]
    } );

    // Add the glucose value and refresh the table data
    var frm = $('#quick_add_form');
    frm.submit(function () {
        $.ajax({
            type: frm.attr('method'),
            url: "{% url 'glucose_quick_add' %}",
            data: frm.serialize(),
            success: function (data) {
                var message = jQuery.parseJSON(data);
                if (message['success']) {
                    // Reload the table data. This function is located in
                    // scripts/scripts.js.
                    oTable.fnReloadAjax();

                    // Reload the chart and stats panels
                    loadStats();
                    loadChart();

                    document.getElementById('quick_add_form').reset();
                    $('#id_value').focus();

                    // Re-enable the submit button.
                    $('#submit-id-submit').prop('disabled', false);
                }
                else {
                    alert(message['error']);
                    $('#id_value').focus().select();

                    // Re-enable the submit button.
                    $('#submit-id-submit').prop('disabled', false);
                }
            },
            error: function(data) {
                alert('Sorry, something went wrong. Please try again.');
            }
        });
        return false;
    });


    // For Twitter button
    function updateTwitterValues(text, via) {
      $('#id_twitter_button').html('<a href="https://twitter.com/share?url=/" class="twitter-share-button" data-dnt="true" data-text="' + text +'" data-count="none" data-via="' + via +'">Tweet</a>');
      twttr.widgets.load();
    }

    !function(d,s,id){
    var js,fjs=d.getElementsByTagName(s)[0];

    if(!d.getElementById(id)){
        js=d.createElement(s);
        js.id=id;
        js.src="https://platform.twitter.com/widgets.js";
        fjs.parentNode.insertBefore(js,fjs);
    }}

    (document,"script","twitter-wjs");
} );
</script>
{% endblock %}

glucosetracker/templates/core/help.html
{% extends 'base.html' %}

{% block heading %}
    <h3><span class="glyphicon glyphicon-question-sign"></span> Help</h3>
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    {% crispy form %}
{% endblock %}